### ISSUE TITLE
Test doesn't wait long enough for search page results to load

### ISSUE THREAD

**Issue by antoniym** [js-soft/wdi5#236]
We observed a test instability while developing a Demokit test journeys in wdi5.

wdio-ui5-service version: 0.9.0-rc4

Manual test steps:
1. Navigate to https://openui5nightly.hana.ondemand.com/
2. In the "Search" field (upper right-hand side) type "OPA" and click Enter to submit the search.

Result:
The test should verify the titles in the search result page ('All (1 - 25 of 132)' and 'Search Results for "OPA"').
However, if the results page loading takes a little longer, the test does not wait for it to load and fails.
If we add an explicit sleep of 5 seconds (await browser.pause(5000)), the page loads completely and the test passes successfully.

Please find the test step as follows:

//Assertions
searchResultsArePresent: async () => {
        var searchResultsPageTitle = await browser.asControl({
            selector: {
                id: "sdk---searchPage--searchTitle",
            }
        });

        var searchResultsListTitle = await browser.asControl({
            selector: {
                controlType: "sap.m.Title",
                viewId: "sdk---searchPage",
                bindingPath: {
                    propertyPath: "/visibleAllLength",
                    modelName: "searchView"
                }
            }
        });

        await browser.pause(5000);
        await expect(await searchResultsListTitle.getText()).toMatch(/All \(1 - /);
        await expect(await (await searchResultsPageTitle.getWebElement()).$('span[id=sdk---searchPage--searchTitle-innerTitle]').getText()).toBe('Search Results for "OPA"');
    }

**Comment by dominikfeininger** [comment]
Can you please provide your `config`

Like the wdio documentation explains (https://webdriver.io/docs/api/browser/pause/), please use (https://webdriver.io/docs/api/element/waitForExist)  `waitForExist` to wait for an element to be loaded.

**Comment by vobu** [comment]
Hi,
could you please update to the most recent version of `wd5`, namely `v0.9.0-rc4.2` and check whether the issue still persists?
Background: we're relying on the UI5-internal (async) event queue to wait until all async operations in the app have resolved. It might be worth investigating how the search on the UI5 site is done/implemented and check from there how to best test it.
Hth, V.

**Comment by antoniym** [comment]
Hi,

Thank you very much for the feedback!

We have tested with the latest version v0.9.0-rc4.2. However, the instability is still observed. We have also noticed one more instability in this test suite, which is also observed in both versions:

Manual test steps:

1. Navigate to https://openui5nightly.hana.ondemand.com/tools
2. Verify that the title of the page is "Tools"

Result:
The test should verify that the title of the page is "Tools"
However, if the title loads slower than the sections below it, the test does not wait for it and fails.

Code:
`
toolsPageTitleIsDisplayed: async () => {
        var expectedToolsPageTitle = "Tools";
        var actualToolsPageTitle = await browser.asControl({
            selector: {
                id: "sdk---tools--landingImageHeadline"
            }
        });

        expect(await actualToolsPageTitle.getText()).toBe(expectedToolsPageTitle);
    },
`

**Comment by vobu** [comment]
well, that might actually be more an issue with the UI5 site being served from the CDN and less an issue of `wdi5` - because we had the same experience when connecting to the UI5 site in our tests. That's why we've refactored those tests and now only connect to "our" servers in the tests.
Long story short: please try not running your tests against the UI5 SDK site :)

**Comment by hmanchev** [comment]
Hi Volker, I don't understand your suggestion. UI5 usually consumed from the CDN - this is the more often case of UI5 users. This means that most of the wdi5 tests will be executed against apps, which are loading UI5 from the CDN.

In our case - the cookie dialog can be easily handled, but the issue here is that the title of the "Tools" page is loading slowly and wdi5 is not synchronizing with the page. I think that such cases can happen in different applications and there should be general solution, but not loading from CDN is not variant. Our test is supposed to be executed against "UI5 SDK site" and I don't understand why wdi5 could require specific app or hostting to synchronize fine.

In my opinion, the test framework shouldn't be dependant of the app or hosting - whether is loading fast or slow.

**Comment by dominikfeininger** [comment]
@hmanchev still ongoing work here?
